#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="${1:-$PROJECT_ROOT/public}"

mkdir -p "$OUTPUT_DIR"
rm -rf "${OUTPUT_DIR:?}"/*

CANVAS_SOURCE="$PROJECT_ROOT/conversation_canvas.html"
CONVERSATION_SOURCE="$PROJECT_ROOT/conversation.md"

if [[ ! -f "$CANVAS_SOURCE" ]]; then
  echo "error: $CANVAS_SOURCE not found" >&2
  exit 1
fi

cp "$CANVAS_SOURCE" "$OUTPUT_DIR/index.html"

if [[ -f "$CONVERSATION_SOURCE" ]]; then
  cp "$CONVERSATION_SOURCE" "$OUTPUT_DIR/conversation.md"
else
  cat <<'MD' > "$OUTPUT_DIR/conversation.md"
# Fractal Intelligence Conversations

_No conversation history has been recorded yet. Use `./scripts/log_conversation.sh` to begin logging exchanges._
MD
fi

cat <<'MD' > "$OUTPUT_DIR/README.md"
# One Engine — Conversation Canvas Bundle

This directory is generated by `scripts/build_canvas_site.sh` and published to GitHub Pages.
The bundle contains:

- `index.html`: the live-updating conversation canvas UI.
- `conversation.md`: the markdown log that powers the canvas view.

To regenerate locally:

```bash
./scripts/build_canvas_site.sh path/to/output
```

Deployments run automatically via GitHub Actions and appear at the repository's Pages URL.
MD
